name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Run tests in Docker
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip * -x '*.git*' '*.github*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          use_existing_version_if_available: true
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-306856845282
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
